//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectRequest()
        {
            this.EmployeeCollectRequests = new HashSet<EmployeeCollectRequest>();
            this.FoodDistributions = new HashSet<FoodDistribution>();
        }
    
        public int CollectRequest_Id { get; set; }
        public string Food_Dscription { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Expired_Time { get; set; }
        public string Address { get; set; }
        public System.DateTime Preffered_Time { get; set; }
        public int DonorId { get; set; }
        public string Status { get; set; }
    
        public virtual FoodDonor FoodDonor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCollectRequest> EmployeeCollectRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodDistribution> FoodDistributions { get; set; }
    }
}
