//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodDistribution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodDistribution()
        {
            this.EmployeeFoodDistributions = new HashSet<EmployeeFoodDistribution>();
        }
    
        public int Distribution_Id { get; set; }
        public string Address { get; set; }
        public System.DateTime Time { get; set; }
        public int CollectRequest_Id { get; set; }
        public string Status { get; set; }
    
        public virtual CollectRequest CollectRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeFoodDistribution> EmployeeFoodDistributions { get; set; }
    }
}
