//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZeroHunger1Entities1 : DbContext
    {
        public ZeroHunger1Entities1()
            : base("name=ZeroHunger1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<CollectRequest> CollectRequests { get; set; }
        public virtual DbSet<EmployeeCollectRequest> EmployeeCollectRequests { get; set; }
        public virtual DbSet<EmployeeFoodDistribution> EmployeeFoodDistributions { get; set; }
        public virtual DbSet<Emplyee> Emplyees { get; set; }
        public virtual DbSet<FoodDistribution> FoodDistributions { get; set; }
        public virtual DbSet<FoodDonor> FoodDonors { get; set; }
    }
}
